# This file will be configured by the user after they create a new site from this template.
backend:
  name: github
  # IMPORTANT: THESE ARE PLACEHOLDERS FOR YOUR CLIENT TO FILL IN
  repo: LorenzoMoriniDev/test-svelte-blog
  branch: main
  # This will point to the client's authentication service
  base_url: https://hidden-math-99f2.lorenzo-morini99.workers.dev

site_url: https://lorenzo-morini99.github.io/test-svelte-blog/

media_folder: "public/images"
public_folder: "test-svelte-blog/images"

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "publishDate", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
